from typing import Protocol
from uuid import UUID

from services.identity.core.domain.entities import User


class UserRepositoryProtocol(Protocol):
    async def get_by_email(self, email: str) -> User: ...
    async def get_by_id(self, user_id: UUID) -> User: ...
    async def create(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...