[project]
name = "wolns-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dishka>=1.5.0",
    "fastapi>=0.115.12",
    "pydantic>=2.10.6",
    "ruff>=0.11.2",
    "sentry-sdk>=2.24.1",
]
